config/routes.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

Nuntium::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :accounts do
    member do
      get :select
    end
    collection do
      post :reclaim
    end
  end

  resources :reclaims

  resources :applications do
    collection do
      put :routing_rules
    end
  end
  resources :channels do
    member do
      get :enable
      get :disable
      get :pause
      get :resume
      get :whitelist
    end
  end
  resources :ao_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :reroute
      post :simulate_route
      get :rgviz
    end
  end
  resources :at_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :simulate_route
      get :rgviz
    end
  end
  resources :logs
  resources :custom_attributes, :except => :show
  resource :interactions
  resource :settings
  resources :members do
    collection do
      get :autocomplete
      post :add
      post :remove
      post :set_user_role
      post :set_user_application_role
      post :set_user_channel_role
    end
  end
  resources :visualizations, :only => :index do
    get :messages_state_by_day, :on => :collection
  end

  scope '/:account_id/clickatell', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'clickatell#index', :as => :clickatell
    match '/ack' => 'clickatell#ack', :as => :clickatell_ack, :constraints => {:account_id => /.*/}
  end

  match '/clickatell/view_credit' => 'clickatell#view_credit', :as => :clickatel_credit

  scope '/channels/twitter' do
    post '/create' => 'twitter#create', :as => :create_twitter_channel
    put '/update/:id' => 'twitter#update', :as => :update_twitter_channel
  end

  scope '/:account_id/shujaa', :constraints => {:account_id => /.*/} do
    match '/incoming/:callback_guid' => 'shujaa#index', :as => :shujaa
  end

  scope '/twitter' do
    match '/callback' => 'twitter#callback', :as => :twitter_callback
  end

  scope '/:account_id/qst', :constraints => {:account_id => /.*/}  do
    post '/incoming' => 'qst_server#push', :as => :qst_push
    get '/incoming' => 'qst_server#get_last_id', :as => :qst_get_last_id, :constraints => {:account_id => /.*/}
    get '/outgoing' => 'qst_server#pull', :as => :qst_pull, :constraints => {:account_id => /.*/}
    match '/setaddress' => 'qst_server#set_address', :as => :qst_set_address, :constraints => {:account_id => /.*/}
  end

  scope '/:account_name/:application_name', :constraints => {:account_name => /.*/, :application_name => /.*/} do
    get '/rss' => 'rss#index', :as => :rss, :format => 'xml'
    post '/rss' => 'rss#create', :as => :create_rss, :constraints => {:account_name => /.*/, :application_name => /.*/}

    match '/send_ao' => 'ao_messages#create_via_api', :as => :send_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
    get '/get_ao' => 'ao_messages#get_ao', :as => :get_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
  end

  match '/:account_id/dtac/incoming' => 'dtac#index', :as => :dtac, :constraints => {:account_id => /.*/}

  scope '/:account_id/ipop/:channel_name', :constraints => {:account_id => /.*/} do
    post '/incoming' => 'ipop#index', :as => :ipop
    post '/ack' => 'ipop#ack', :as => :ipop_ack, :constraints => {:account_id => /.*/}
  end

  scope '/:account_id/twilio', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'twilio#index', :as => :twilio
    match '/ack' => 'twilio#ack', :as => :twilio_ack
  end

  scope '/api' do

    scope '/users' do
      match '/request_token' => 'api_user_authentication#request_token', :as => :request_token, :via => :get
    end

    scope '/carriers' do
      match '/' => 'api_carrier#index', :as => :carriers
      match '/:guid' => 'api_carrier#show', :as => :carrier
    end

    scope '/countries' do
      match '/' => 'api_country#index', :as => :countries
      match '/:iso' => 'api_country#show', :as => :country
    end

    scope '/user_channels' do
      match '/' => 'api_user_channel#index', :as => :user_channels
    end

    scope '/channels' do
      get '/' => 'api_channel#index', :as => :api_channels_index
      post '/' => 'api_channel#create', :as => :api_channels_create
      get '/:name' => 'api_channel#show', :as => :api_channels_show
      put '/:name' => 'api_channel#update', :as => :api_channels_update
      delete '/:name' => 'api_channel#destroy', :as => :api_channels_destroy
      get '/:name/twitter/friendships/create' => 'api_twitter_channel#friendship_create', :as => :api_twitter_follow
      get '/:name/twitter/authorize' => 'api_twitter_channel#authorize', :as => :api_twitter_authorize
      get '/:name/xmpp/add_contact' => 'api_xmpp_channel#add_contact', :as => :api_xmpp_add_contact
    end

    get '/candidate/channels' => 'api_channel#candidates', :as => :api_candidate_channels

    scope '/custom_attributes' do
      get '/' => 'api_custom_attributes#show', :as => :api_custom_attributes_show
      post '/' => 'api_custom_attributes#create_or_update', :as => :api_custom_attributes_show
    end
  end

  scope '/tickets' do
    post '/' => 'tickets#create'
    get '/:code' => 'tickets#show'
  end

  root :to => 'applications#index'
end

app/models/messages/ao_message.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

class AoMessage < ActiveRecord::Base
  belongs_to :account
  belongs_to :application
  belongs_to :channel
  has_many :logs
  has_many :children, :foreign_key => 'parent_id', :class_name => name
  has_many :ao_message_fragments

  validates_presence_of :account
  serialize :custom_attributes, Hash
  serialize :original, Hash

  after_save :send_delivery_ack
  before_save :route_failover

  before_save :truncate_body, :if => :fragment
  after_save :untruncate_body, :if => :fragment

  include MessageCommon
  include MessageGetter
  include MessageSerialization
  include MessageCustomAttributes
  include MessageSearch
  include MessageFragmentation

  # Logs that each message was delivered/not delivered through the given interface
  def self.log_delivery(msgs, account, interface)
    msgs.each do |msg|
      if msg.tries < account.max_tries
        account.logger.ao_message_delivery_succeeded msg, interface
      else
        account.logger.ao_message_delivery_exceeded_tries msg, interface
      end
    end
  end

  def send_succeed(account, channel, channel_relative_id = nil)
    self.state = 'delivered'
    self.channel_relative_id = channel_relative_id unless channel_relative_id.nil?
    self.save!

    account.logger.message_channeled self, channel
  end

  def send_failed(account, channel, exception)
    self.state = 'failed'
    self.save!

    account.logger.exception_in_channel_and_ao_message channel, self, exception
  end

  def reset_to_original
    return unless original.present?
    original.each do |key, value|
      if Fields.include? key.to_s
        self.send "#{key}=", value
      else
        self.custom_attributes[key.to_s] = value
      end
    end
  end

  private

  def send_delivery_ack
    return unless changed? && changes.keys != ["updated_at"]

    return true unless state == 'failed' || state == 'delivered' || state == 'confirmed'
    return true unless channel_id

    app = self.application
    return true unless app and app.delivery_ack_method != 'none'

    Queues.publish_application app, SendDeliveryAckJob.new(account_id, application_id, id, state)
    true
  end

  def route_failover
    return unless state_was != 'failed' && state == 'failed'
    return unless self.failover_channels.present?

    chans = self.failover_channels.split(',')
    chan = account.channels.find_by_id chans[0]

    self.failover_channels = chans[1 .. -1].join(',')
    self.failover_channels = nil if self.failover_channels.empty?

    return unless chan

    reset_to_original

    ThreadLocalLogger.reset
    ThreadLocalLogger << "Re-route failover"
    chan.route_ao self, 're-route', :dont_save => true
  end

  def truncate_body
    @body_before_truncate = body
    self.body = self.body[0 ... 65000]
  end

  def untruncate_body
    self.body = @body_before_truncate
  end
end

app/controllers/ao_messages_controller.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

class AoMessagesController < ApplicationController
  include ApplicationAuthenticatedController
  include CustomAttributesControllerCommon

  skip_filter :check_login, :only => [:create_via_api, :get_ao]
  before_filter :authenticate, :only => [:create_via_api, :get_ao]

  def index
    @page = params[:page].presence || 1
    @search = params[:search]
    @previous_search = params[:previous_search]
    @page = 1 if @previous_search.present? && @previous_search != @search

    @ao_messages = account.ao_messages.includes(:channel, :application).order 'id DESC'
    @ao_messages = @ao_messages.search @search, :account => account if @search.present?
    @ao_messages = @ao_messages.paginate :page => @page, :per_page => ResultsPerPage
    @ao_messages = @ao_messages.all
  end

  def new
    @msg = AoMessage.new
    @kind = 'ao'
    render "messages/new"
  end

  def create
    msg = account.ao_messages.new params[:ao_message]
    msg.custom_attributes = get_custom_attributes
    msg.application.route_ao msg, 'user'

    redirect_to ao_messages_path, :notice => %Q(AO Message was created with id #{msg.id} <a href="#{ao_message_path(msg)}" target="_blank">view log</a> <a href="#{thread_ao_message_path(msg)}" target="_blank">view thread</a>).html_safe
  end

  def show
    @msg = account.ao_messages.find_by_id params[:id]
    @hide_title = true
    @logs = account.logs.where(:ao_message_id => @msg.id).order(:created_at).all
    @kind = 'ao'
    render "messages/message"
  end

  def thread
    @msg = account.ao_messages.find_by_id params[:id]
    @address = @msg.to
    @hide_title = true
    @page = (params[:page] || '1').to_i

    limit = @page * 5
    aos = account.ao_messages.includes(:application, :channel).where(:to => @address, :parent_id => nil).order('ao_messages.id DESC').limit(limit)
    ats = account.at_messages.includes(:application, :channel).where(:from => @address).order('at_messages.id DESC').limit(limit)

    @has_more = aos.length == limit || ats.length == limit

    @msgs = aos + ats
    @msgs.sort!{|x, y| y.created_at <=> x.created_at}

    render "messages/thread"
  end

  def mark_as_cancelled
    messages = get_selected_messages
    messages.each { |msg| msg.state = 'cancelled'; msg.save! }

    flash[:notice] = "#{messages.length} Application Originated messages #{messages.length == 1 ? 'was' : 'were'} marked as cancelled"
    params[:action] = :index
    redirect_to params
  end

  def reroute
    messages = get_selected_messages
    messages.each { |msg| msg.application.reroute_ao msg if msg.application }

    flash[:notice] = "#{messages.length} Application Originated #{messages.length == 1 ? 'message was' : 'messages were'} re-routed"
    params[:action] = :index
    redirect_to params
  end

  def simulate_route
    @msg = account.ao_messages.new params[:ao_message]
    @msg.custom_attributes = get_custom_attributes

    @result = @msg.application.route_ao @msg, 'ui', :simulate => true
    @hide_title = true
  end

  def create_via_api
    case params[:format]
    when nil
      create_single
    when 'json'
      create_many_json
    when 'xml'
      create_many_xml
    end
  end

  # GET /:account_name/:application_name/get_ao.:format
  def get_ao
    render :json => AoMessage.find_all_by_application_id_and_token(@application.id, params[:token])
  end

  def rgviz
    render :rgviz => AoMessage, :conditions => ['ao_messages.account_id = ?', account.id], :extensions => true
  end

  private

  def get_selected_messages
    messages = account.ao_messages.includes(:application)
    if params[:ao_all].to_b
      messages = messages.search params[:search], :account => account if params[:search].present?
    else
      messages = messages.where 'id IN (?)', params[:ao_messages]
    end
    messages.all
  end

  def create_single
    msg = AoMessage.from_hash params
    msg.token = params.delete(:token) || Guid.new.to_s
    route msg

    response.headers['X-Nuntium-Id'] = msg.id.to_s
    response.headers['X-Nuntium-Guid'] = msg.guid.to_s
    response.headers['X-Nuntium-Token'] = msg.token.to_s
    head :ok
  end

  def create_many_json
    create_many :from_json
  end

  def create_many_xml
    create_many :parse_xml
  end

  def create_many(method)
    token = Guid.new.to_s
    AoMessage.send(method, request.raw_post) do |msg|
      token = msg.token if msg.token
      msg.token = token
      route msg
    end
    response.headers['X-Nuntium-Token'] = token
    head :ok
  end

  def route(msg)
    msg.account_id = @account.id
    msg.token ||= Guid.new.to_s
    @application.route_ao msg, 'http'
  end
end

app/views/ao_messages/index.html.erb
<p>
Messages sent from your application into Nuntium and then into the world are called Application Originated messages. <a href="http://code.google.com/p/nuntium/wiki/Messages#Application_Originated_messages" target="_blank">Learn more...</a>
</p>

<form id="ao_messages_form" action="#ao">
<input type="hidden" name="page" value="<%= @page -%>" />
<input type="hidden" name="previous_search" value="<%= @search -%>" />
<input type="hidden" id="ao_all" name="ao_all" value="0" />

<%- if applications.empty? -%>
  <%= link_to 'Create an Application', new_application_path -%> to create AO Messages.<br/><br/>
<%- else -%>
  <%= link_to '<img src="/assets/new_message.png" width="16" height="16" style="position:relative; top:4px" alt="Create new AO Message">Create new AO Message'.html_safe, new_ao_message_path -%> &nbsp; &nbsp;
<%- end -%>
Search: <input type="text" name="search" value="<%= @search.try(:html_safe) -%>" size="50" class="<%= @search.present? ? 'highlighted' : '' -%>"/> <a href="http://code.google.com/p/nuntium/wiki/AdvancedSearch" target="_blank" title="You can filter by field like 'id:5', 'before:&quot;20 minutes ago&quot;', 'state:queued', etc.">?</a> &nbsp; &nbsp;
Select: <%= link_to_function 'all', 'select_all_ao_messages()' -%>, <%= link_to_function 'none', 'select_none_ao_messages()' -%> &nbsp; &nbsp;
Actions: <%= link_to_function 'mark as cancelled', 'mark_ao_messages_as_cancelled()' -%>, <%= link_to_function 're-route', 'reroute_ao_messages()' -%>

<div><%= page_entries_info @ao_messages, :model => 'message' -%></div>
<%= will_paginate @ao_messages, :param_name => 'page', :params => { :previous_search => @search } -%>

<div id="all_ao_messages_text" style="display:none"></div>
<%- if @ao_messages.present? -%>
  <table border="1" class="table">
    <tr>
      <th></th>
      <th>When</th>
      <th>Id</th>
      <th>Guid</th>
      <th>Channel Relative Id</th>
      <th>From</th>
      <th>To</th>
      <th>Subject</th>
      <th>Body</th>
      <th>Channel</th>
      <th>Application</th>
      <th>Tries</th>
      <th>State</th>
      <th></th>
    </tr>
    <tr>
    <%- @ao_messages.each_with_index do |msg, i| -%>
      <tr class="<%= i.even_to_s -%>">
        <td><input type="checkbox" name="ao_messages[]" value="<%= msg.id -%>" <%= 'checked="checked"' if !params[:ao_messages].nil? && params[:ao_messages].include?(msg.id.to_s) -%>/></td>
        <td>
          <%- if msg.parent_id
            image_name = @ao_messages[i+1] && @ao_messages[i+1].parent_id == msg.parent_id ? 'branch' : 'branch_end'
            -%>
            <%= image_tag "#{image_name}.png", :size => '16x16', :style => 'position:relative; top:4px' -%>
          <%- end -%>
          <%= time_ago msg.timestamp -%>
        </td>
        <td align="right"><%= msg.id -%></td>
        <td><%= short_html msg.guid -%></td>
        <td><%= short_html msg.channel_relative_id -%></td>
        <td><%= msg.from -%></td>
        <td><a hre<%= link_to msg.to, thread_ao_message_path(msg), :target => '_blank' if msg.to.present? -%></td>
        <td><%= short_html message_subject(msg) -%></td>
        <td><%= short_html message_body(msg) -%></td>
        <td><%= msg.channel.try(:name) -%></td>
        <td><%= msg.application.try(:name) -%></td>
        <td align="right"><%= msg.tries -%></td>
        <td><%= msg.state -%></td>
        <td>
          <%= link_to 'view log', msg, :target => '_blank'%>
        </td>
      </tr>
    <%- end -%>
  </table>
<%- end -%>

<%= will_paginate @ao_messages, :param_name => 'page', :params => { :previous_search => @search } -%>
</form>

<script>
var total_ao_messages = <%= @ao_messages.total_entries -%>;
var current_ao_messages = <%= @ao_messages.length -%>;
<%-
if !params[:ao_all].nil? && params[:ao_all].to_b
  -%>
  select_all_pages_ao_messages();
  <%-
end
-%>
</script>

app/views/ao_messages/simulate_route.html.erb
<h4>Route simulation</h4>

<%- if @result[:strategy] == 'broadcast' -%>
  <div>Message was broadcasted.</div>
  <%- @result[:messages].each_with_index do |msg, i| -%>
    <%= render 'messages/message', :msg => msg, :title => (i == 0 ? 'Original copy' : "Broadcasted copy #{i}"), :log => @result[:logs][i] -%>
  <%- end -%>
<%- elsif @strategy == 'single_priority' -%>
  <div id="route_simulation">
  <%= @result[:channel].name -%>
  </div>
  <%= render 'messages/message', :msg => @msg, :title => 'Details', :log => @result[:log] -%>
<%- else -%>
   <div id="route_simulation">
   No channel for the given message.
   </div>
   <%= render 'messages/message', :msg => @msg, :title => 'Details', :log => @result[:log] -%>
<%- end -%>