config/routes.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

Nuntium::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :accounts do
    member do
      get :select
    end
    collection do
      post :reclaim
    end
  end

  resources :reclaims

  resources :applications do
    collection do
      put :routing_rules
    end
  end
  resources :channels do
    member do
      get :enable
      get :disable
      get :pause
      get :resume
      get :whitelist
    end
  end
  resources :ao_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :reroute
      post :simulate_route
      get :rgviz
    end
  end
  resources :at_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :simulate_route
      get :rgviz
    end
  end
  resources :logs
  resources :custom_attributes, :except => :show
  resource :interactions
  resource :settings
  resources :members do
    collection do
      get :autocomplete
      post :add
      post :remove
      post :set_user_role
      post :set_user_application_role
      post :set_user_channel_role
    end
  end
  resources :visualizations, :only => :index do
    get :messages_state_by_day, :on => :collection
  end

  scope '/:account_id/clickatell', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'clickatell#index', :as => :clickatell
    match '/ack' => 'clickatell#ack', :as => :clickatell_ack, :constraints => {:account_id => /.*/}
  end

  match '/clickatell/view_credit' => 'clickatell#view_credit', :as => :clickatel_credit

  scope '/channels/twitter' do
    post '/create' => 'twitter#create', :as => :create_twitter_channel
    put '/update/:id' => 'twitter#update', :as => :update_twitter_channel
  end

  scope '/:account_id/shujaa', :constraints => {:account_id => /.*/} do
    match '/incoming/:callback_guid' => 'shujaa#index', :as => :shujaa
  end

  scope '/twitter' do
    match '/callback' => 'twitter#callback', :as => :twitter_callback
  end

  scope '/:account_id/qst', :constraints => {:account_id => /.*/}  do
    post '/incoming' => 'qst_server#push', :as => :qst_push
    get '/incoming' => 'qst_server#get_last_id', :as => :qst_get_last_id, :constraints => {:account_id => /.*/}
    get '/outgoing' => 'qst_server#pull', :as => :qst_pull, :constraints => {:account_id => /.*/}
    match '/setaddress' => 'qst_server#set_address', :as => :qst_set_address, :constraints => {:account_id => /.*/}
  end

  scope '/:account_name/:application_name', :constraints => {:account_name => /.*/, :application_name => /.*/} do
    get '/rss' => 'rss#index', :as => :rss, :format => 'xml'
    post '/rss' => 'rss#create', :as => :create_rss, :constraints => {:account_name => /.*/, :application_name => /.*/}

    match '/send_ao' => 'ao_messages#create_via_api', :as => :send_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
    get '/get_ao' => 'ao_messages#get_ao', :as => :get_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
  end

  match '/:account_id/dtac/incoming' => 'dtac#index', :as => :dtac, :constraints => {:account_id => /.*/}

  scope '/:account_id/ipop/:channel_name', :constraints => {:account_id => /.*/} do
    post '/incoming' => 'ipop#index', :as => :ipop
    post '/ack' => 'ipop#ack', :as => :ipop_ack, :constraints => {:account_id => /.*/}
  end

  scope '/:account_id/twilio', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'twilio#index', :as => :twilio
    match '/ack' => 'twilio#ack', :as => :twilio_ack
  end

  scope '/api' do

    scope '/users' do
      match '/request_token' => 'api_user_authentication#request_token', :as => :request_token, :via => :get
    end

    scope '/carriers' do
      match '/' => 'api_carrier#index', :as => :carriers
      match '/:guid' => 'api_carrier#show', :as => :carrier
    end

    scope '/countries' do
      match '/' => 'api_country#index', :as => :countries
      match '/:iso' => 'api_country#show', :as => :country
    end

    scope '/user_channels' do
      match '/' => 'api_user_channel#index', :as => :user_channels
    end

    scope '/channels' do
      get '/' => 'api_channel#index', :as => :api_channels_index
      post '/' => 'api_channel#create', :as => :api_channels_create
      get '/:name' => 'api_channel#show', :as => :api_channels_show
      put '/:name' => 'api_channel#update', :as => :api_channels_update
      delete '/:name' => 'api_channel#destroy', :as => :api_channels_destroy
      get '/:name/twitter/friendships/create' => 'api_twitter_channel#friendship_create', :as => :api_twitter_follow
      get '/:name/twitter/authorize' => 'api_twitter_channel#authorize', :as => :api_twitter_authorize
      get '/:name/xmpp/add_contact' => 'api_xmpp_channel#add_contact', :as => :api_xmpp_add_contact
    end

    get '/candidate/channels' => 'api_channel#candidates', :as => :api_candidate_channels

    scope '/custom_attributes' do
      get '/' => 'api_custom_attributes#show', :as => :api_custom_attributes_show
      post '/' => 'api_custom_attributes#create_or_update', :as => :api_custom_attributes_show
    end
  end

  scope '/tickets' do
    post '/' => 'tickets#create'
    get '/:code' => 'tickets#show'
  end

  root :to => 'applications#index'
end

app/controllers/application_controller.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  # protect_from_forgery # See ActionController::RequestForgeryProtection for details

  ResultsPerPage = 10

  expose(:account) { current_user.try(:current_account) }
  expose(:user_account) { current_user.user_accounts.where(account_id: account.id).first }
  expose(:account_admin?) { user_account.try(:role) == 'admin' }

  expose(:user_applications) { current_user.user_applications.where(account_id: account.id).all }

  expose(:applications) do
    apps = account.applications
    unless account_admin?
      apps = apps.where(id: user_applications.map(&:application_id))
    end
    apps
  end
  expose(:application)

  expose(:user_channels) { current_user.user_channels.where(account_id: account.id).all }

  expose(:channels) do
    chans = account.channels.includes(:application)
    unless account_admin?
      chans = chans.where("id IN (?) or application_id IN (?)", user_channels.map(&:channel_id), user_applications.map(&:application_id))
    end
    chans
  end
  expose(:channel) do
    channel = if params[:id] || params[:channel_id]
                channel = channels.find(params[:id] || params[:channel_id])
                channel.attributes = params[:channel] if params[:channel]
                channel
              elsif params[:channel]
                params[:channel][:kind].to_channel.new params[:channel]
              elsif params[:kind]
                params[:kind].to_channel.new
              else
                Channel.new
              end
    channel
  end

  expose(:app_routing_rules) { account.app_routing_rules }

  def application_admin?(application)
    return true if account_admin?
    user_applications.find { |ua| ua.application_id == application.id }.try(:role) == 'admin'
  end
  helper_method :application_admin?

  def channel_admin?(channel)
    return true if account_admin?
    (user_channels.find { |uc| uc.channel_id == channel.id }.try(:role) == 'admin') ||
      (user_applications.find { |ua| ua.application_id == channel.application_id }.try(:role) == 'admin')
  end
  helper_method :channel_admin?

  before_filter :check_login
  def check_login
    authenticate_user!
  end

  before_filter :check_account
  def check_account
    redirect_to new_account_path if user_signed_in? && !account
  end

  def check_account_admin
    redirect_to root_path unless account_admin?
  end
end

app/controllers/applications_controller.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

class ApplicationsController < ApplicationController
  include RulesControllerCommon

  before_filter :set_application_parameters, :only => [:create, :update]
  before_filter :check_account_admin, :only => [:create, :routing_rules]
  before_filter :check_application_admin, :only => [:edit, :update, :destroy]

  def set_application_parameters
    application.account_id = account.id
    application.ao_rules = get_rules :aorules
    application.at_rules = get_rules :atrules
  end

  def create
    if application.save
      redirect_to applications_path, :notice => "Application #{application.name} created"
    else
      render :new
    end
  end

  def update
    if application.save
      redirect_to applications_path, :notice => "Application #{application.name} updated"
    else
      render :edit
    end
  end

  def destroy
    application.destroy
    redirect_to applications_path, :notice => "Application #{application.name} deleted"
  end

  def routing_rules
    account.app_routing_rules = get_rules :apprules

    if account.save
      redirect_to applications_path, :notice => 'Application Routing Rules were changed'
    else
      render 'index'
    end
  end

  private

  def check_application_admin
    redirect_to applications_path unless application_admin?(application)
  end
end

app/helpers/application_helper.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
  def short(msg, length = 15)
    return '' if msg.nil?
    msg.length > length ? (msg[0 ... length] + "...") : msg
  end

  def short_html(msg, length = 15)
    ('<span title="' << (h msg) << '">' << h(short(msg, length)) << '</span>').html_safe
  end

  def message_subject(msg)
    if can_view_message?(msg)
      msg.subject
    else
      '*' * (msg.subject.try(:length) || 0)
    end
  end

  def message_body(msg)
    if can_view_message?(msg)
      msg.body
    else
      '*' * (msg.body.try(:length) || 0)
    end
  end

  def can_view_message?(msg)
    return true if account_admin?

    app_access = !msg.application_id || user_applications.find { |ua| ua.application_id == msg.application_id }
    channel_access = msg.channel_id && user_channels.find { |ua| ua.channel_id == msg.channel_id }
    app_access || channel_access
  end

  def time_ago(time)
    return '' if time.nil?
    ('<span title="' << time.utc.to_s << '">' << time_ago_in_words(time.utc, true) << ' ago</span>').html_safe
  end

  def go_back_link
    link_to 'Go back', :controller => :home, :action => :index
  end

  def nuntium_version
    begin
      @@nuntium_version = File.read('VERSION').strip unless defined? @@nuntium_version
    rescue Errno::ENOENT
      @@nuntium_version = 'Development'
    end
    @@nuntium_version
  end
end

app/views/applications/_form.html.erb
<%- content_for :head do -%>
  <script type="text/javascript" charset="utf-8">
  function interface_rss() {
    $('#config').hide();
  }
  function interface_qst_client() {
    $('#config').show();
    $('#custom_format').hide();
  }
  function interface_http_get_callback() {
    $('#config').show();
    $('#custom_format').show();
    $('#custom_format_desc').html("Custom HTTP GET format");
  }
  function interface_http_post_callback() {
    $('#config').show();
    $('#custom_format').show();
    $('#custom_format_desc').html("Custom HTTP POST format");
  }

  function delivery_ack_none() {
    $('#delivery_ack_config').hide();
  }
  function delivery_ack_get() {
    $('#delivery_ack_config').show();
  }
  function delivery_ack_post() {
    $('#delivery_ack_config').show();
  }

  $(function() {
    interface_<%= application.interface || 'rss' -%>();
    delivery_ack_<%= application.delivery_ack_method -%>();
  });
  </script>
<%- end -%>

<%-
# Write the applications in javascript so we can fill the combobox without
# going to the server...
applications_names = applications.map(&:name).compact.sort!
-%>
<script type="text/javascript">
var applications = <%= applications_names.to_json.html_safe -%>;
</script>

<%= form_for application do |f| -%>
  <%= f.error_messages -%>

  <%- if application.new_record? -%>
    <p>
    <%= f.label :name -%><br/>
    <%= f.text_field :name -%>
    </p>
  <%- end -%>

  <p>
  <%- unless application.new_record? -%>
    <b>Leave blank if you don't want to change the password</b><br/>
  <%- end -%>
  <%= f.label :password -%><br/>
  <%= f.password_field :password, :value => '', :autocomplete => :off -%>
  </p>
  <p>
  <%= f.label :password_confirmation -%><br/>
  <%= f.password_field :password_confirmation, :value => '', :autocomplete => :off -%>
  </p>

  <%= f.label :interface -%><br/>
  <%= f.radio_button :interface, 'rss', :onclick => "interface_rss();" -%> <%= f.label :interface, 'Rss', :value => 'rss' -%><br/>
  <%= f.radio_button :interface, 'qst_client', :onclick => "interface_qst_client();"%> <%= f.label :interface, 'QST client', :value => 'qst_client' -%><br/>
  <%= f.radio_button :interface, 'http_get_callback', :onclick => "interface_http_get_callback();"%> <%= f.label :interface, 'HTTP GET callback', :value => 'http_get_callback' -%><br/>
  <%= f.radio_button :interface, 'http_post_callback', :onclick => "interface_http_post_callback();"%> <%= f.label :interface, 'HTTP POST callback', :value => 'http_post_callback' -%><br/>

  <div id="config">
    <h5>Interface configuration:</h5>
    <p>
    <%= f.label :url -%><br/>
    <%= f.text_field :interface_url, :class => 'configurl' -%>
    </p>
    <p>
    <%= f.label :user -%><br/>
    <%= f.text_field :interface_user, :class => 'configurl' -%>
    </p>
    <p>
    <%= f.label :password -%><br/>
    <%= f.password_field :interface_password, :autocomplete => :off, :class => 'configurl' -%>
    </p>
    <p id="custom_format">
    <%= f.label :custom_format, '<span id="custom_format_desc" /></span> (leave blank for default) <a href="http://code.google.com/p/nuntium/wiki/Interfaces#Custom_formats" target="_blank">Learn more...</a>'.html_safe -%><br/>
    <%= f.text_area :interface_custom_format, :rows => 3, :cols => 80 -%>
    </p>
  </div>

  <h5>Routing configuration:</h5>

  <p>
  Route via last AT channel used <acronym title="When an AO message needs to be routed, if it's 'to' field matches the 'from' field of the last AT message received, the channel used to receieve that AT message will be used.">?</acronym><br/>
  <%= f.radio_button :use_address_source, 0, :checked => !application.use_address_source? -%> <%= f.label :use_address_source, 'No', :value => 0 -%><br/>
  <%= f.radio_button :use_address_source, 1, :checked => application.use_address_source? -%> <%= f.label :use_address_source, 'Yes', :value => 1 -%>
  </p>

  <p>
  Strategy:<br/>
  <%- ['broadcast', 'single_priority'].each do |strategy| -%>
    <%= f.radio_button :strategy, strategy, :checked => application.strategy == strategy -%> <%= f.label :strategy, Application.strategy_description(strategy), :value => strategy -%><br/>
  <%- end -%>
  </p>

  <h5>Delivery acknowledgement:</h5>

  <p>
  This callback will be invoked when an AO message's state changes to either 'failed', 'delivered' or 'confirmed'.
  </p>

  <p>
  Method:<br/>
  <%- ['none', 'get', 'post'].each do |method| -%>
    <%= f.radio_button :delivery_ack_method, method, :checked => application.delivery_ack_method == method, :onclick => "delivery_ack_#{method}();" -%> <%= f.label :delivery_ack_method, Application.delivery_ack_method_description(method), :value => method -%><br/>
  <%- end -%>
  </p>

  <div id="delivery_ack_config">
  <p>
  <%= f.label :url -%>:<br/>
  <%= f.text_field :delivery_ack_url -%>
  </p>
  <p>
  <%= f.label :user -%>:<br/>
  <%= f.text_field :delivery_ack_user -%>
  </p>
  <p>
  <%= f.label :password -%>:<br/>
  <%= f.password_field :delivery_ack_password -%>
  </p>
  </div>

  <h5>AO Rules</h5>

  <p>
  These rules will be executed when an AO message is received via this application.
  <a href="http://code.google.com/p/nuntium/wiki/Rules" target="_blank">Learn more...</a>
  </p>

  <div class="aorules"></div>

  <script type="text/javascript">
  jQuery(function(){
      init_rules(jQuery('.aorules'), 'aorules', <%= application.ao_rules.to_json.html_safe -%>, {exclude: ['application']}, {exclude: ['application']});
  });
  </script>

  <h5>AT Rules</h5>

  <p>
  These rules will be executed when an AT message is sent to this application.
  <a href="http://code.google.com/p/nuntium/wiki/Rules" target="_blank">Learn more...</a>
  </p>

  <div class="atrules"></div>

  <script type="text/javascript">
  jQuery(function(){
      init_rules(jQuery('.atrules'), 'atrules', <%= application.at_rules.to_json.html_safe -%>, {exclude: ['application']}, {exclude: ['application']});
  });
  </script>

  <h5>Twitter</h5>

  <p>
  If you want your application's users to create channels on behalf of another Twitter Application
  (not the Nuntium Application), enter its consumer key and secret here.
  </p>

  <p>
  <%= f.label :twitter_consumer_key -%>:<br/>
  <%= f.password_field :twitter_consumer_key, size: 60 -%>
  </p>

  <p>
  <%= f.label :twitter_consumer_secret -%>:<br/>
  <%= f.password_field :twitter_consumer_secret, size: 60 -%>
  </p>

  <%= submit_tag (application.new_record? ? 'Create Application' : 'Update Application') -%>
<%- end -%>

app/views/applications/edit.html.erb
<h4>Edit <%= application.name -%> Application</h4>

<%= render 'form' %>

<%= link_to 'Go back', applications_path -%>

app/views/applications/index.slim
p
  ' A Nuntium Application simply represents your application.<br/>
  ' If you have many applications you would create many Nuntium Applications, and you can choose to interface with each of them in a different way.

- if account_admin?
  p= link_to 'Create new Application', new_application_path

- if applications.present?
  table.table cellspacing="4"
    tr
      th Name
      th Interface
      th Route via last channel?
      th Strategy
      th Delivery ACK
      th
    - applications.each_with_index do |app, i|
      tr class="#{i.even_to_s}"
        td= app.name
        td= app.interface_description
        td= app.use_address_source? ? 'Yes' : 'No'
        td= app.strategy_description
        td= app.delivery_ack_method_description
        td
          =' link_to "view log", logs_path(:search => "application:#{app.name}")
          =' link_to "view aos", ao_messages_path(:search => "application:#{app.name}")
          =' link_to "view ats", at_messages_path(:search => "application:#{app.name}")
          - if application_admin?(app)
            =' link_to "edit", edit_application_path(app)
            =' link_to "delete", app, :method => :delete, :confirm => "Are you sure you want to delete the application #{app.name}?"

- if account_admin?
  h5 Application Routing Rules

  - applications_names = applications.map(&:name).sort!
  - if applications_names.length < 2
    p No need to specify these rules right now since you don't have more than one application.
  - else
    - if app_routing_rules.blank?
      p#errorNotice
        ' Now that you have more than one application you should configure rules
        ' to determine the application an AT message is routed to.
    - if account
      = form_for account, :url => routing_rules_applications_path do |f|
        = f.error_messages
        p
          ' Specify here rules to route AT messages to specific applications.<br/>
          ' These rules will not be executed if an AT message is received via a channel that belongs to an application<br/>
          ' or when a message specifies the custom attribute "application".
          a href="http://code.google.com/p/nuntium/wiki/Rules" target="_blank" Learn more...

        p
          b Here you can only determine the target application. To change an AT message's attributes specify AT rules for each application.

        .apprules

        javascript:
          var applications = #{applications_names.to_json.html_safe};
          jQuery(function(){
              init_rules(jQuery('.apprules'), 'apprules', #{app_routing_rules.to_json.html_safe}, null, {include: ['application']});
          });

        = submit_tag 'Update rules'

  p Routing can also be manipulated setting #{link_to 'custom attributes', custom_attributes_path} to specific users.

app/views/applications/new.html.erb
<h4>New Application</h4>

<%= render 'form' %>

<%= link_to 'Go back', applications_path -%>