config/routes.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

Nuntium::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :accounts do
    member do
      get :select
    end
    collection do
      post :reclaim
    end
  end

  resources :reclaims

  resources :applications do
    collection do
      put :routing_rules
    end
  end
  resources :channels do
    member do
      get :enable
      get :disable
      get :pause
      get :resume
      get :whitelist
    end
  end
  resources :ao_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :reroute
      post :simulate_route
      get :rgviz
    end
  end
  resources :at_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :simulate_route
      get :rgviz
    end
  end
  resources :logs
  resources :custom_attributes, :except => :show
  resource :interactions
  resource :settings
  resources :members do
    collection do
      get :autocomplete
      post :add
      post :remove
      post :set_user_role
      post :set_user_application_role
      post :set_user_channel_role
    end
  end
  resources :visualizations, :only => :index do
    get :messages_state_by_day, :on => :collection
  end

  scope '/:account_id/clickatell', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'clickatell#index', :as => :clickatell
    match '/ack' => 'clickatell#ack', :as => :clickatell_ack, :constraints => {:account_id => /.*/}
  end

  match '/clickatell/view_credit' => 'clickatell#view_credit', :as => :clickatel_credit

  scope '/channels/twitter' do
    post '/create' => 'twitter#create', :as => :create_twitter_channel
    put '/update/:id' => 'twitter#update', :as => :update_twitter_channel
  end

  scope '/:account_id/shujaa', :constraints => {:account_id => /.*/} do
    match '/incoming/:callback_guid' => 'shujaa#index', :as => :shujaa
  end

  scope '/twitter' do
    match '/callback' => 'twitter#callback', :as => :twitter_callback
  end

  scope '/:account_id/qst', :constraints => {:account_id => /.*/}  do
    post '/incoming' => 'qst_server#push', :as => :qst_push
    get '/incoming' => 'qst_server#get_last_id', :as => :qst_get_last_id, :constraints => {:account_id => /.*/}
    get '/outgoing' => 'qst_server#pull', :as => :qst_pull, :constraints => {:account_id => /.*/}
    match '/setaddress' => 'qst_server#set_address', :as => :qst_set_address, :constraints => {:account_id => /.*/}
  end

  scope '/:account_name/:application_name', :constraints => {:account_name => /.*/, :application_name => /.*/} do
    get '/rss' => 'rss#index', :as => :rss, :format => 'xml'
    post '/rss' => 'rss#create', :as => :create_rss, :constraints => {:account_name => /.*/, :application_name => /.*/}

    match '/send_ao' => 'ao_messages#create_via_api', :as => :send_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
    get '/get_ao' => 'ao_messages#get_ao', :as => :get_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
  end

  match '/:account_id/dtac/incoming' => 'dtac#index', :as => :dtac, :constraints => {:account_id => /.*/}

  scope '/:account_id/ipop/:channel_name', :constraints => {:account_id => /.*/} do
    post '/incoming' => 'ipop#index', :as => :ipop
    post '/ack' => 'ipop#ack', :as => :ipop_ack, :constraints => {:account_id => /.*/}
  end

  scope '/:account_id/twilio', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'twilio#index', :as => :twilio
    match '/ack' => 'twilio#ack', :as => :twilio_ack
  end

  scope '/api' do

    scope '/users' do
      match '/request_token' => 'api_user_authentication#request_token', :as => :request_token, :via => :get
    end

    scope '/carriers' do
      match '/' => 'api_carrier#index', :as => :carriers
      match '/:guid' => 'api_carrier#show', :as => :carrier
    end

    scope '/countries' do
      match '/' => 'api_country#index', :as => :countries
      match '/:iso' => 'api_country#show', :as => :country
    end

    scope '/user_channels' do
      match '/' => 'api_user_channel#index', :as => :user_channels
    end

    scope '/channels' do
      get '/' => 'api_channel#index', :as => :api_channels_index
      post '/' => 'api_channel#create', :as => :api_channels_create
      get '/:name' => 'api_channel#show', :as => :api_channels_show
      put '/:name' => 'api_channel#update', :as => :api_channels_update
      delete '/:name' => 'api_channel#destroy', :as => :api_channels_destroy
      get '/:name/twitter/friendships/create' => 'api_twitter_channel#friendship_create', :as => :api_twitter_follow
      get '/:name/twitter/authorize' => 'api_twitter_channel#authorize', :as => :api_twitter_authorize
      get '/:name/xmpp/add_contact' => 'api_xmpp_channel#add_contact', :as => :api_xmpp_add_contact
    end

    get '/candidate/channels' => 'api_channel#candidates', :as => :api_candidate_channels

    scope '/custom_attributes' do
      get '/' => 'api_custom_attributes#show', :as => :api_custom_attributes_show
      post '/' => 'api_custom_attributes#create_or_update', :as => :api_custom_attributes_show
    end
  end

  scope '/tickets' do
    post '/' => 'tickets#create'
    get '/:code' => 'tickets#show'
  end

  root :to => 'applications#index'
end

app/views/shared/_create_channel.slim
- channel_kinds = [['Create new...', '']] + Channel.kinds
- channel_kinds[1..-1].map!{|x| x[0] << ' channel'; x}
= select_tag('new_channel', options_for_select(channel_kinds), :onchange => 'create_channel(this)')

app/views/shared/_edit_custom_attributes.erb
<%-
include_channels = defined?(include_channels) ? include_channels : false
as_restriction = defined?(as_restriction) ? as_restriction : false
custom_attributes = entity.nil? ? {} : (as_restriction ? entity.restrictions : entity.custom_attributes)
show_accept_when_not_specified_option = defined?(accept_when_not_specified_option) ? accept_when_not_specified_option : true
-%>

<%-
if as_restriction
  -%>
  <h5>Restrictions</h5>
  <p>
  An AO message will not be routed to this channel if its fields or custom attributes do not match those of this channel's restrictions.
  <a href="http://code.google.com/p/nuntium/wiki/Channels#Channel_Filter_Phase" target="_blank">Learn more...</a>
  </p>
  <%-
else
  -%>
  <h5>Custom Attributes</h5>
  <p>
  <%-
  if @kind == 'ao'
    -%>
    Used by channels' restrictions. Can also override the routing strategy or specify the channel to be routed to.
    <%-
  else
    -%>
    Can override the application this message will be routed to.
    <%-
  end
  -%>
  <a href="http://code.google.com/p/nuntium/wiki/Messages#Custom_attributes" target="_blank">Learn more...</a>
  </p>
  <%-
end
-%>

<%-
# Write the applications in javascript so we can fill the combobox without
# going to the server...
applications = account.applications.map(&:name).sort!
channels = account.channels.map(&:name).sort!
countries = Country.all
carriers = Carrier.all_with_countries
-%>
<script type="text/javascript">
var applications = <%= applications.to_json.html_safe -%>;
var channels = <%= channels.to_json.html_safe -%>;
var show_accept_when_not_specified_option = <%= show_accept_when_not_specified_option ? 'true' : 'false' -%>;
</script>

<div>
<ul id="custom_attributes">
  <%-
  def write_custom_attribute(applications, channels, countries, carriers, include_channels, as_restriction, show_accept_when_not_specified_option, name, values)
    values = [values] unless values.kind_of? Array
    values.each do |value|
      next if value == '' and name != ''

      is_custom = name != "" && name != "application" && name != "country" && name != "carrier"
      -%>
      <li>
        <select name="<%= is_custom ? 'doesnt_matter' : 'custom_attribute_name[]'%>" onchange="channel_custom_attribute_changed(this)">
          <option value="" <%= 'selected="selected"' if name == "" -%>>Add <%= as_restriction ? 'a restriction' : 'an attribute' -%>...</option>
          <%- if applications.length > 0 -%>
            <option value="application" <%= 'selected="selected"' if name == "application" -%>>Application</option>
          <%- end -%>
          <option value="country" <%= 'selected="selected"' if name == "country" -%>>Country</option>
          <option value="carrier" <%= 'selected="selected"' if name == "carrier" -%>>Carrier</option>
          <%- if include_channels and channels.length > 0 -%>
            <option value="suggested_channel" <%= 'selected="selected"' if name == "suggested_channel" -%>>Suggested channel</option>
          <%- end -%>
          <option value="custom" <%= 'selected="selected"' if is_custom -%>>Custom</option>
        </select>
        <span class="value">
        <%-
        case name
        when 'application'
          -%>
          =
          <select name="custom_attribute_value[]">
            <%- applications.each do |app| -%>
              <option <%= 'selected="selected"' if app == value -%>><%= app -%></option>
            <%- end -%>
          </select>
          <%-
        when 'country'
          -%>
          =
          <select name="custom_attribute_value[]">
            <%- countries.each do |country| -%>
              <option value="<%= country.iso2 -%>" <%= 'selected="selected"' if country.iso2.casecmp(value) == 0 -%>><%= country.name -%></option>
            <%- end -%>
          </select>
          <%-
        when 'carrier'
          selected_carrier = carriers.select{|x| x.guid == value}.first
          -%>
          =
          <select name="doesnt_matter" onchange="channel_custom_attribute_country_changed(this)">
            <%- countries.each do |country| -%>
              <option value="<%= country.iso2 -%>" <%= 'selected="selected"' if selected_carrier.country.id == country.id -%>><%= country.name -%></option>
            <%- end -%>
          </select>
          <span class="value2">
            <select name="custom_attribute_value[]">
              <%- carriers.select{|x| x.country.iso2 == selected_carrier.country.iso2}.each do |carrier| -%>
                <option value="<%= carrier.guid -%>" <%= 'selected="selected"' if selected_carrier.guid == carrier.guid -%>><%= carrier.name -%></option>
              <%- end -%>
            </select>
          </span>
          <%-
        when ''
          nil # Nothing
        else
          -%>
          Name: <input type="text" name="custom_attribute_name[]" value="<%= h name -%>"> Value: <input type="text" name="custom_attribute_value[]" value="<%= h value -%>">
        <%-
        end
        -%>

        <%- if name != '' -%>
          <%- if show_accept_when_not_specified_option -%>
            &nbsp;
            <input type="hidden" name="custom_attribute_optional[]" value="0"/>
            <input type="checkbox" name="custom_attribute_optional[]" value="1" <%= 'checked="checked"' if values.include? '' -%>/> Accept when not specified
          <%- end -%>
          &nbsp; <a href="javascript:void(0)" onclick="remove_custom_attribute(this)">Remove</a>
        <%- end -%>
        </span>
       </li>
      <%-
    end
  end

  custom_attributes.each do |name, values|
    write_custom_attribute applications, channels, countries, carriers, include_channels, as_restriction, show_accept_when_not_specified_option, name, values
  end
  write_custom_attribute applications, channels, countries, carriers, include_channels, as_restriction, show_accept_when_not_specified_option, '', ''
  -%>
</ul>
</div>
<br/>

app/views/shared/_reclaim_account.erb
<p>If you already own an account, fill this form and you'll become its administrator.</p>

<%= form_for :account, url: reclaim_accounts_path do |f| -%>
  <input type="hidden" name="from_reclaim" value="<%= from_reclaim %>"/>
  <% if @acount_reclaim_error %>
  <p style="color: red">Invalid account name/password</p>
  <% end %>

  <p>
  <%= f.label :name -%><br/>
  <%= f.text_field :name -%>
  </p>

  <p>
  <%= f.label :password -%><br/>
  <%= f.password_field :password, :value => '', :autocomplete => :off -%>
  </p>

  <%= f.submit 'Reclaim Account' %>
<%- end -%>

app/views/shared/_tabs.erb
<ul id="tabs">
  <%-
    [
      ['Applications', :applications],
      ['Channels', :channels],
      ['AO messages', :ao_messages],
      ['AT messages', :at_messages],
      ['Logs', :logs],
      ['Interactions', :interactions],
      ['Members', :members],
      ['Settings', :settings],
      ['Reclaim Account', :reclaims],
      ['Visualizations', :visualizations]
    ].each do |name, action|
    -%>
      <li<%= (params[:controller].to_sym == action ? ' class="selected"' : '').html_safe %>><%= link_to name, eval("#{action}_path") -%></li>
    <%-
  end
  -%>
</ul>