config/routes.rb
# Copyright (C) 2009-2012, InSTEDD
#
# This file is part of Nuntium.
#
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

Nuntium::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :accounts do
    member do
      get :select
    end
    collection do
      post :reclaim
    end
  end

  resources :reclaims

  resources :applications do
    collection do
      put :routing_rules
    end
  end
  resources :channels do
    member do
      get :enable
      get :disable
      get :pause
      get :resume
      get :whitelist
    end
  end
  resources :ao_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :reroute
      post :simulate_route
      get :rgviz
    end
  end
  resources :at_messages do
    member do
      get :thread
    end
    collection do
      post :mark_as_cancelled
      post :simulate_route
      get :rgviz
    end
  end
  resources :logs
  resources :custom_attributes, :except => :show
  resource :interactions
  resource :settings
  resources :members do
    collection do
      get :autocomplete
      post :add
      post :remove
      post :set_user_role
      post :set_user_application_role
      post :set_user_channel_role
    end
  end
  resources :visualizations, :only => :index do
    get :messages_state_by_day, :on => :collection
  end

  scope '/:account_id/clickatell', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'clickatell#index', :as => :clickatell
    match '/ack' => 'clickatell#ack', :as => :clickatell_ack, :constraints => {:account_id => /.*/}
  end

  match '/clickatell/view_credit' => 'clickatell#view_credit', :as => :clickatel_credit

  scope '/channels/twitter' do
    post '/create' => 'twitter#create', :as => :create_twitter_channel
    put '/update/:id' => 'twitter#update', :as => :update_twitter_channel
  end

  scope '/:account_id/shujaa', :constraints => {:account_id => /.*/} do
    match '/incoming/:callback_guid' => 'shujaa#index', :as => :shujaa
  end

  scope '/twitter' do
    match '/callback' => 'twitter#callback', :as => :twitter_callback
  end

  scope '/:account_id/qst', :constraints => {:account_id => /.*/}  do
    post '/incoming' => 'qst_server#push', :as => :qst_push
    get '/incoming' => 'qst_server#get_last_id', :as => :qst_get_last_id, :constraints => {:account_id => /.*/}
    get '/outgoing' => 'qst_server#pull', :as => :qst_pull, :constraints => {:account_id => /.*/}
    match '/setaddress' => 'qst_server#set_address', :as => :qst_set_address, :constraints => {:account_id => /.*/}
  end

  scope '/:account_name/:application_name', :constraints => {:account_name => /.*/, :application_name => /.*/} do
    get '/rss' => 'rss#index', :as => :rss, :format => 'xml'
    post '/rss' => 'rss#create', :as => :create_rss, :constraints => {:account_name => /.*/, :application_name => /.*/}

    match '/send_ao' => 'ao_messages#create_via_api', :as => :send_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
    get '/get_ao' => 'ao_messages#get_ao', :as => :get_ao, :constraints => {:account_name => /.*/, :application_name => /.*/}
  end

  match '/:account_id/dtac/incoming' => 'dtac#index', :as => :dtac, :constraints => {:account_id => /.*/}

  scope '/:account_id/ipop/:channel_name', :constraints => {:account_id => /.*/} do
    post '/incoming' => 'ipop#index', :as => :ipop
    post '/ack' => 'ipop#ack', :as => :ipop_ack, :constraints => {:account_id => /.*/}
  end

  scope '/:account_id/twilio', :constraints => {:account_id => /.*/} do
    match '/incoming' => 'twilio#index', :as => :twilio
    match '/ack' => 'twilio#ack', :as => :twilio_ack
  end

  scope '/api' do

    scope '/users' do
      match '/request_token' => 'api_user_authentication#request_token', :as => :request_token, :via => :get
    end

    scope '/carriers' do
      match '/' => 'api_carrier#index', :as => :carriers
      match '/:guid' => 'api_carrier#show', :as => :carrier
    end

    scope '/countries' do
      match '/' => 'api_country#index', :as => :countries
      match '/:iso' => 'api_country#show', :as => :country
    end

    scope '/user_channels' do
      match '/' => 'api_user_channel#index', :as => :user_channels
    end

    scope '/channels' do
      get '/' => 'api_channel#index', :as => :api_channels_index
      post '/' => 'api_channel#create', :as => :api_channels_create
      get '/:name' => 'api_channel#show', :as => :api_channels_show
      put '/:name' => 'api_channel#update', :as => :api_channels_update
      delete '/:name' => 'api_channel#destroy', :as => :api_channels_destroy
      get '/:name/twitter/friendships/create' => 'api_twitter_channel#friendship_create', :as => :api_twitter_follow
      get '/:name/twitter/authorize' => 'api_twitter_channel#authorize', :as => :api_twitter_authorize
      get '/:name/xmpp/add_contact' => 'api_xmpp_channel#add_contact', :as => :api_xmpp_add_contact
    end

    get '/candidate/channels' => 'api_channel#candidates', :as => :api_candidate_channels

    scope '/custom_attributes' do
      get '/' => 'api_custom_attributes#show', :as => :api_custom_attributes_show
      post '/' => 'api_custom_attributes#create_or_update', :as => :api_custom_attributes_show
    end
  end

  scope '/tickets' do
    post '/' => 'tickets#create'
    get '/:code' => 'tickets#show'
  end

  root :to => 'applications#index'
end

app/controllers/visualizations_controller.rb
# Copyright (C) 2009-2012, InSTEDD
# 
# This file is part of Nuntium.
# 
# Nuntium is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Nuntium is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Nuntium.  If not, see <http://www.gnu.org/licenses/>.

class VisualizationsController < ApplicationController
  def messages_state_by_day
    @selected_tab = :visualizations
    @kind = params[:kind]
    @kind = 'ao' unless @kind == 'ao' || @kind == 'at'
    @two_months_ago = Date.today - 2.months
    if @two_months_ago.year == Date.today.year
      @prefix = "#{Date.today.year}-"
      @month_and_day = "concat(month(updated_at), '-', day(updated_at))"
    else
      @month_and_day = "concat(toDate(updated_at))"
    end
    @two_months_ago = @two_months_ago.strftime '%Y-%m-%d'
    render 'messages_state_by_day'
  end
end

app/views/visualizations/index.html.erb
<p>
<%= link_to 'State of AO messages for the last two months', messages_state_by_day_visualizations_path(:kind => :ao) %><br/>
See the amount of failed, queued, delivered and confirmed AO messages along the days. Clicking on the graph shows you a pie
of those messages by channel.
</p>
<p>
<%= link_to 'State of AT messages for the last two months', messages_state_by_day_visualizations_path(:kind => :at) %><br/>
See the amount of failed, queued, delivered and confirmed AT messages along the days. Clicking on the graph shows you a pie
of those messages by channel.
</p>

app/views/visualizations/messages_state_by_day.html.erb
<div id="loading_states">Loading, please wait...</div>
<%= rgviz :id => 'states',
  :kind => 'ColumnChart',
  :url => eval("rgviz_#{@kind}_messages_path"),
  :query => "select #{@month_and_day}, count(id) where updated_at >= '#{@two_months_ago}' group by #{@month_and_day} pivot state order by #{@month_and_day} label count(id) 'messages'",
  :options => {:width => '100%', :height => '300', :isStacked => true, :title => "State of #{@kind.to_s.upcase} messages for the last two months"},
  :events => {:select => 'select_state', :rgviz_start => "show_loading", :rgviz_end => "hide_loading"},
  :extensions => true
%>

<div id="loading_channels" style="display:none">Loading, please wait...</div>
<div style="text-align:center">
<%= rgviz :id => 'channels',
  :kind => 'PieChart',
  :url => eval("rgviz_#{@kind}_messages_path"),
  :query => "select channel_name, count(id) where toDate(updated_at) = param_1 and state = param_2 group by channel_name",
  :options => {:width => '700', :height => '600', :title => 'js_channels_title'},
  :events => {:select => 'select_channel', :rgviz_start => "show_loading", :rgviz_end => "hide_loading"},
  :extensions => true
%>
</div>

<%= link_to 'Go back', visualizations_path -%>

<script>
var current_date;
var current_state;

function select_state(e) {
  var selection = rgviz_states.getSelection();
  if (selection.length != 1) return;

  var item = selection[0];
  current_date = rgviz_states_data.getValue(item.row, 0);
  <%= "current_date = '#{@prefix}' + current_date;" if @prefix %>
  current_state = rgviz_states_data.getColumnLabel(item.column);
  current_state = current_state.substring(0, current_state.length - 9);
  var pieces = current_date.split('-')
  rgviz_draw_channels(current_date, current_state);
}

function select_channel(e) {
  var selection = rgviz_states.getSelection();
  if (selection.length != 1) return;

  var item = selection[0];
  var channel = rgviz_channels_data.getValue(item.row, 0);

  window.location = '/#{@kind}_messages/?search=channel:' + channel + ' state:' + current_state + ' updated_at:' + current_date;
}

function channels_title(e) {
  return current_state + " messages per channel at " + current_date;
}

function show_loading(viz) {
  $('#loading_' + viz).show();
}

function hide_loading(viz) {
  $('#loading_' + viz).hide();
}
</script>